# Generated by Django 5.0.7 on 2024-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_nick",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите tg_id",
                max_length=50,
                null=True,
                verbose_name="Tg_id",
            ),
        ),
    ]
