# Generated by Django 5.0.7 on 2024-07-18 11:12

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите где?", max_length=100,
                        verbose_name="Место"
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=datetime.date(2024, 7, 18),
                        help_text="Укажите когда?",
                        verbose_name="Время в формате YYYY-MM-DD hh-mm",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите совершаемое действие",
                        max_length=100,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Можно привязать к полезной привычке",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("once a day", "1 раз в день"),
                            ("every 2 days", "каждые 2 дня"),
                            ("every 3 days", "каждые 3 дня"),
                            ("every 4 days", "каждые 4 дня"),
                            ("every 5 days", "каждые 5 дней"),
                            ("every 6 days", "каждые 6 дней"),
                            ("once a week", "1 раз в неделю"),
                        ],
                        default="once a day",
                        help_text="Укажите периодичность привычки",
                        max_length=25,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Указывается только для полезной привычки, "
                                  "если нет привязки к приятной",
                        max_length=100,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=60),
                        help_text="Укажите продолжительность выполнения",
                        verbose_name="время на выполнение в секундах",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Можно публиковать в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("action",),
            },
        ),
    ]
