# Generated by Django 5.0.7 on 2024-07-21 16:27

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="duration",
        ),
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца привычки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="period_time",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Укажите продолжительность выполнения",
                verbose_name="время на выполнение в секундах",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Указывается только для полезной привычки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="связанная приятная привычка",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователи",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                default=datetime.date(2024, 7, 21),
                help_text="Укажите когда?",
                verbose_name="Время в формате YYYY-MM-DD hh-mm",
            ),
        ),
    ]
