# Generated by Django 5.0.7 on 2024-07-23 10:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_period_habit_periodicity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="users",
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                default=datetime.date(2024, 7, 23),
                help_text="Укажите когда?",
                verbose_name="Время в формате YYYY-MM-DD hh-mm",
            ),
        ),
    ]
