# Generated by Django 5.0.7 on 2024-07-25 13:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_remove_habit_users_alter_habit_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="habit_date",
            field=models.DateField(
                default=datetime.date(2024, 7, 25),
                verbose_name="Укажите дату начала выполнения привычки ГГ-ММ-ДД",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="period_time",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Укажите продолжительность выполнения",
                verbose_name="время на выполнение в секундах",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default=datetime.time(13, 31, 33, 274693),
                help_text="Укажите когда?",
                verbose_name="Время в формате MM-DD",
            ),
        ),
    ]
