# Generated by Django 5.0.7 on 2024-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_habit_habit_date_alter_habit_period_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="habit_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Укажите дату начала выполнения привычки ГГ-ММ-ДД",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default="12:00:00",
                help_text="Укажите когда?",
                verbose_name="Время в формате MM-ЧЧ",
            ),
        ),
    ]
